export const CART_FETCH_DATA_SUCCESS = 'CART_FETCH_DATA_SUCCESS';
export const CART_IS_LOADING = 'CART_IS_LOADING';
export const ITEM_LIST_IS_LOADING = 'ITEM_LIST_IS_LOADING';
export const ITEM_SUBMIT_IS_LOADING = 'ITEM_SUBMIT_IS_LOADING';
export const ITEM_SUBMIT_SUCCESS = 'ITEM_SUBMIT_SUCCESS';
